language: node_js
node_js:
  - 5.9.0
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ruby-full
before_script:
  - gem install scss_lint --no-rdoc --no-ri
script: make test
