---
# tasks file for cartertdte.mta

- name: Instala paquetes Base
  yum: name={{ item }} state=present
  with_items:
    - "{{ system_packages }}"

- name: Copia resolv.conf
  copy: src=resolv.conf dest=/etc/resolv.conf

- name: Copia pdns.repo
  copy: src=pdns.repo dest=/etc/yum.repos.d/pdns.repo

- name: Instala pdns
  yum: name=pdns state=present

- name: Instala mysql
  yum: name=pdns-backend-mysql state=present

- name: "Copia NGinx FS"
  copy: src=nginx-filesystem-1.10.0-8.p5.0.29.el6.noarch.rpm dest=/tmp/nginx-filesystem-1.10.0-8.p5.0.29.el6.noarch.rpm

- name: "Copia NGinx"
  copy: src=nginx-1.10.0-8.p5.0.29.el6.x86_64.rpm dest=/tmp/nginx-1.10.0-8.p5.0.29.el6.x86_64.rpm

- name: Copia repo de Nodejs
  copy: src=node.repo dest=/etc/yum.repos.d/nodesource-el.repo

- name: Instal CentOS Software collections
  yum: name=centos-release-SCL state=present

- name: Copia repo de Passenger
  copy: src=passenger.repo dest=/etc/yum.repos.d/passenger.repo

- name: Desactiva SELINUX
  selinux: state=disabled

- name: Instala todos los Fucking paquetes
  yum: name={{ item }} state=present disable_gpg_check=yes
  with_items:
    - nodejs
    - passenger
    - ruby193
    - curl-devel
    - ruby193-ruby-devel
    - ruby193-rubygems-devel
    - GeoIP
    - gd
    - gperftools
    - pcre
    - libev
    - git

- name: instala NginxFS
  yum: name=/tmp/nginx-filesystem-1.10.0-8.p5.0.29.el6.noarch.rpm state=present

- name: instala Nginx
  yum: name=/tmp/nginx-1.10.0-8.p5.0.29.el6.x86_64.rpm state=present

- name: "Elimina configuracion default de nginx"
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: Copia configuracion para PowerDNS
  copy: src=pdns-nginx.conf dest=/etc/nginx/conf.d/pdns-nginx.conf

- name: Copia configuracion de ZBox RBAC
  copy: src=zbox-rbac-manager.conf dest=/etc/nginx/conf.d/zbox-rbac-manager.conf

- name: Clona Repo de ZBox RBAC
  git: repo=https://github.com/ZBoxApp/zbox-manager-rbac.git dest=/var/www/zbox-manager-rbac/ update=yes

- name: Instala modules de node para ZBoxRBAC
  npm: path=/var/www/zbox-manager-rbac/

- name: Copia configuracion para ZBOXRBAC
  copy: src=zboxrbac-conf.json dest=/var/www/zbox-manager-rbac/config.json

- name: Copia config de passenger
  copy: src=passenger.conf dest=/etc/nginx/conf.d/passenger.conf

- lineinfile: dest=/etc/nginx/nginx.conf regexp="^env NODE_TLS" line='env NODE_TLS_REJECT_UNAUTHORIZED=0;'
- lineinfile: dest=/etc/nginx/nginx.conf regexp="^env zbox_rbac_config" line='env zbox_rbac_config=/var/www/zbox-manager-rbac/config.json;'

- name: reinicia Nginx
  service: name=nginx state=restarted

- name: Copia hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    mode: '0644'

- name: Desahbilita postfix
  service: name=postfix state=stopped enabled=no

- name: Desahbilita iptables
  service: name=iptables state=stopped enabled=no
